name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - setup.sh
      - action.yaml
      - .github/workflows/workflow.yaml
jobs:
  lint_shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Flutter action
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter --version
